
export const GET_IMAGES_REQUEST = "GET_IMAGES_REQUEST"
export const GET_IMAGES_SUCCESS = "GET_IMAGES_SUCCESS"
export const GET_IMAGES_FAIL = "GET_IMAGES_FAIL"

export const ADD_NEW_IMAGE_REQUEST = "ADD_NEW_IMAGE_REQUEST"
export const ADD_NEW_IMAGE_SUCESS = "ADD_NEW_IMAGE_SUCESS"
export const ADD_NEW_IMAGE_FAIL = "ADD_NEW_IMAGE_FAIL"