export const ADD_NEW_USER_REQUEST = "ADD_NEW_USER_REQUEST"
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS"
export const ADD_NEW_USER_FAIL = "ADD_NEW_USER_FAIL"


export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT = "LOGOUT"

export const GET_USER_DETALES_REQUEST = "GET_USER_DETALES_REQUEST"
export const GET_USER_DETALES_SUCCESS = "GET_USER_DETALE_SUCCESS"
export const GET_USER_DETALES_FAIL = "GET_USER_DETALES_FAIL"